// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly VITE_AUTH_DISABLED: string;
  readonly BACKEND_URI: string;
  readonly AUTH_IDP: string;
  readonly AUTH_CLIENT_ID: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
